### ISSUE TITLE
关于播放同步问题和音量调整

### ISSUE THREAD

**Issue by diaolingge** [BetterNCM/PlayWithBilibili#11]
在使用的过程中遇到以下问题

播放时视频与音乐不同步？卸载后重新安装发现正常 切换其他歌曲再次不同步

可以添加一个选项使调取得视频文件不播放声音或者调整音量 仅充当背景不做同步音乐和视频但好像又不太适合

登录入口不够明显

**Comment by std-microblock** [comment]
建议下次不同问题发不同issue

**Comment by wldll** [comment]
希望能有个向前跳视频进度的选项，在我这里视频一般会落后音频6秒左右
