### ISSUE TITLE
内存占用过大

### ISSUE THREAD

**Issue by EatKFCinMc** [BetterNCM/PlayWithBilibili#4]
![QQ截图20230313212014](https://user-images.githubusercontent.com/69470365/224715243-9978ac87-e0f7-4fd6-97c5-874824540f03.png)
如图，加上插件后网易云内存占用达到1.3G左右，实测仅删除此插件后恢复正常

**Comment by std-microblock** [comment]
和正在播放当前歌曲的bilibili网页版对比看看
