### ISSUE TITLE
自动同步进度

### ISSUE THREAD

**Issue by xycld** [BetterNCM/PlayWithBilibili#9]
视频加载完成后自动和歌曲同步进度，不然视频的进度会比歌曲慢

**Comment by std-microblock** [comment]
现在的行为是如果相差超过0.5s则重新同步

**Comment by xycld** [comment]
至少我现在跳转进度的时候他没同步，正常播放的时候相差也肯定不止5秒，我看看能不能交pr吧，或者您那边方便直接改了吧

**Comment by xycld** [comment]
而且我如果暂停，他一直在跑

**Comment by SNOCEI** [comment]
还有，有时候歌曲播放一部分后重启网易云时如果歌曲有记忆的播放进度，或者有进度跳转时不会自动同步进度，暂停也不会让视频跟着暂停，我这边情况也差不多，有时候切了歌还会导致失效，不知道为什么也无法复现，重启就好了，建议添加个手动同步的按钮

**Comment by lihaqi** [comment]
确实，目前进度不同步，一直都是重音

**Comment by hai9740** [comment]
能不能吧声音关了啊，重音的。可以用播放器的声音，bibilili的只要画面，不要声音。
